### ISSUE TITLE
i face following problem when transfer BEP20

### ISSUE THREAD

**Issue by maijshaikh** [Fenguoz/bsc-php#9]
i face following problem when transfer
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid private key format. in /home/bk5cstaking/public_html/bep20_new/vendor/fenguoz/bsc-php/src/PEMHelper.php:97
Stack trace:
#0 /home/bk5cstaking/public_html/bep20_new/vendor/fenguoz/bsc-php/src/PEMHelper.php(83): Binance\PEMHelper::privateKeyToPublicKey('0x5475F17bC4EE2...')
#1 /home/bk5cstaking/public_html/bep20_new/vendor/fenguoz/bsc-php/src/BEP20.php(37): Binance\PEMHelper::privateKeyToAddress('0x5475F17bC4EE2...')
#2 /home/bk5cstaking/public_html/bep20_new/example.php(37): Binance\BEP20->transfer('0x5475F17bC4EE2...', '0x38E9b9302443d...', 1)
#3 {main}
  thrown in /home/bk5cstaking/public_html/bep20_new/vendor/fenguoz/bsc-php/src/PEMHelper.php on line 97

What to do i dont understand...

**Comment by Fenguoz** [comment]
“Invalid private key format”
